"""add_channel_stats_for_v2

Revision ID: 2bf42a55d31c
Revises: 879501cba57d
Create Date: 2026-01-12 01:05:08.910081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf42a55d31c'
down_revision: Union[str, None] = '879501cba57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('avg_views_30d', sa.Float(), nullable=True))
    op.add_column('channels', sa.Column('avg_forwards_30d', sa.Float(), nullable=True))
    op.add_column('channels', sa.Column('median_engagement_rate', sa.Float(), nullable=True))
    op.add_column('channels', sa.Column('posts_count_30d', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('stats_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'stats_updated_at')
    op.drop_column('channels', 'posts_count_30d')
    op.drop_column('channels', 'median_engagement_rate')
    op.drop_column('channels', 'avg_forwards_30d')
    op.drop_column('channels', 'avg_views_30d')
    # ### end Alembic commands ###
