"""add novelty score to posts

Revision ID: 879501cba57d
Revises: 003
Create Date: 2026-01-12 00:11:33.046274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '879501cba57d'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('novelty_score', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('novelty_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_posts_novelty_score', 'posts', ['novelty_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_novelty_score', table_name='posts')
    op.drop_column('posts', 'novelty_explanation')
    op.drop_column('posts', 'novelty_score')
    # ### end Alembic commands ###
