"""add_posts_per_day_for_v4

Revision ID: bff5f0c20b7c
Revises: 2bf42a55d31c
Create Date: 2026-01-12 01:49:03.663518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff5f0c20b7c'
down_revision: Union[str, None] = '2bf42a55d31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('posts_per_day_30d', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'posts_per_day_30d')
    # ### end Alembic commands ###
